# Generated by Django 6.0.4 on 2026-05-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('youtube_url', models.URLField(verbose_name='URL do YouTube')),
                ('youtube_video_id', models.CharField(blank=True, editable=False, max_length=20, verbose_name='ID do Vídeo')),
                ('youtube_playlist_id', models.CharField(blank=True, editable=False, max_length=50, verbose_name='ID da Playlist')),
                ('channel_handle', models.CharField(blank=True, editable=False, max_length=100, verbose_name='Handle do Canal')),
                ('video_type', models.CharField(blank=True, choices=[('video', 'Vídeo'), ('playlist', 'Playlist'), ('channel', 'Canal')], editable=False, max_length=10, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('public', 'Público'), ('hidden', 'Oculto')], default='draft', max_length=10, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Vídeo / Recurso',
                'verbose_name_plural': 'Vídeos / Recursos',
                'ordering': ['-id'],
            },
        ),
    ]
