# Generated by Django 6.0.4 on 2026-05-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition_number', models.PositiveIntegerField(verbose_name='Número da Edição')),
                ('year', models.PositiveIntegerField(verbose_name='Ano')),
                ('theme', models.CharField(max_length=255, verbose_name='Tema')),
                ('dates', models.CharField(blank=True, max_length=255, verbose_name='Datas')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Local')),
                ('proceedings_url', models.URLField(blank=True, help_text='URL externa para os anais em PDF', verbose_name='Link dos Anais')),
                ('playlist_url', models.URLField(blank=True, verbose_name='Link da Playlist (YouTube)')),
            ],
            options={
                'verbose_name': 'Edição Anterior',
                'verbose_name_plural': 'Edições Anteriores',
                'ordering': ['-year'],
            },
        ),
    ]
