# Generated by Django 6.0.4 on 2026-05-03 19:27

import django.core.files.storage
import django.db.models.deletion
import pathlib
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proceedings', '0001_initial'),
        ('submissions', '0002_submission_decision_notes_submission_final_modality_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_pdf', models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/home/hugo/Documents/LAPAN/dev/cbnv-website/protected_media')), upload_to='', verbose_name='PDF final')),
                ('presentation_file', models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/home/hugo/Documents/LAPAN/dev/cbnv-website/protected_media')), upload_to='', verbose_name='Apresentação')),
                ('video_url', models.URLField(blank=True, verbose_name='Link do vídeo (YouTube)')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Recebido em')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Validado em')),
                ('notes', models.TextField(blank=True, verbose_name='Notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_material', to='submissions.submission', verbose_name='Submissão')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Validado por')),
            ],
            options={
                'verbose_name': 'Material final',
                'verbose_name_plural': 'Materiais finais',
            },
        ),
    ]
