# Generated by Django 6.0.4 on 2026-05-07 14:44

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proceedings', '0002_finalmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalmaterial',
            name='final_pdf',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/app/protected_media')), upload_to='', verbose_name='PDF final'),
        ),
        migrations.AlterField(
            model_name='finalmaterial',
            name='presentation_file',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/app/protected_media')), upload_to='', verbose_name='Apresentação'),
        ),
    ]
