# Generated by Django 6.0.5 on 2026-05-08 20:45

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proceedings', '0003_alter_finalmaterial_final_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalmaterial',
            name='final_pdf',
            field=models.FileField(blank=True, storage=core.storage.ProtectedMediaStorage(), upload_to='', verbose_name='PDF final'),
        ),
        migrations.AlterField(
            model_name='finalmaterial',
            name='presentation_file',
            field=models.FileField(blank=True, storage=core.storage.ProtectedMediaStorage(), upload_to='', verbose_name='Apresentação'),
        ),
    ]
