# Generated by Django 6.0.5 on 2026-05-13 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proceedings', '0005_add_edition_photo'),
        ('videos', '0002_videoresource_locale_videoresource_translation_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalmaterial',
            name='publication_authorized',
            field=models.BooleanField(default=False, help_text='Obrigatório para publicação do trabalho nos anais do evento.', verbose_name='Autorizo a publicação nos anais'),
        ),
        migrations.AddField(
            model_name='finalmaterial',
            name='video_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_materials', to='videos.videoresource', verbose_name='Recurso de vídeo publicado'),
        ),
    ]
