# Generated by Django 6.0.4 on 2026-05-02 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='CBNV 2026', max_length=255, verbose_name='Nome do Evento')),
                ('edition', models.CharField(default='XII', max_length=10, verbose_name='Edição')),
                ('theme', models.CharField(default='Neurovisão na Era da Inteligência Artificial', max_length=255, verbose_name='Tema')),
                ('dates', models.CharField(default='11 a 13 de novembro de 2026', max_length=255, verbose_name='Datas')),
                ('location', models.CharField(default='CAD-1 — UFMG, Belo Horizonte, MG', max_length=255, verbose_name='Local')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail de Contato')),
                ('registration_link', models.URLField(blank=True, verbose_name='Link de Inscrição')),
                ('livestream_link', models.URLField(blank=True, verbose_name='Link de Transmissão')),
                ('fapemig_text', models.TextField(blank=True, verbose_name='Texto FAPEMIG')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('twitter_url', models.URLField(blank=True, verbose_name='X / Twitter')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Configurações do Site',
            },
        ),
    ]
