# Generated by Django 6.0.4 on 2026-05-03 03:00

import django.db.models.deletion
import uuid
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_coresettings_locale_coresettings_translation_key_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('menu_items', wagtail.fields.StreamField([('link', 4)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Rótulo'}), 1: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Página', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'label': 'URL Externa', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Ex: #sobre', 'label': 'Âncora', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('label', 0), ('page', 1), ('url', 2), ('anchor', 3)]], {})}, verbose_name='Itens do Menu')),
            ],
            options={
                'verbose_name': 'Menu do Site',
            },
        ),
        migrations.AlterModelOptions(
            name='coresettings',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='coresettings',
            name='unique_translation_key_locale_core_coresettings',
        ),
        migrations.AlterUniqueTogether(
            name='coresettings',
            unique_together={('translation_key', 'locale')},
        ),
        migrations.AddField(
            model_name='sitemenu',
            name='locale',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale'),
        ),
        migrations.AddField(
            model_name='sitemenu',
            name='site',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site'),
        ),
        migrations.AddConstraint(
            model_name='sitemenu',
            constraint=models.UniqueConstraint(fields=('translation_key', 'locale'), name='unique_translation_key_locale_core_sitemenu'),
        ),
    ]
