# Generated by Django 6.0.5 on 2026-05-09 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_coresettings_logo'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coresettings',
            options={'verbose_name': 'Configurações centrais do site'},
        ),
        migrations.AlterUniqueTogether(
            name='coresettings',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='city',
            field=models.CharField(blank=True, default='Belo Horizonte', max_length=120, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='country',
            field=models.CharField(blank=True, default='Brasil', max_length=80, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='default_seo_description',
            field=models.TextField(blank=True, verbose_name='Descrição SEO padrão'),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='default_seo_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Título SEO padrão'),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de término'),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='fapemig_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logotipo FAPEMIG'),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='format_label',
            field=models.CharField(blank=True, default='Presencial', max_length=80, verbose_name='Formato'),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='google_maps_url',
            field=models.URLField(blank=True, verbose_name='Google Maps'),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='livestream_status',
            field=models.CharField(choices=[('available', 'Disponível'), ('coming_soon', 'Em breve'), ('unavailable', 'Indisponível')], default='coming_soon', help_text='Controla se a transmissão deve aparecer como link ativo, em breve ou indisponível.', max_length=20, verbose_name='Status da transmissão'),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='registration_status',
            field=models.CharField(choices=[('available', 'Disponível'), ('coming_soon', 'Em breve'), ('unavailable', 'Indisponível')], default='coming_soon', help_text="Controla se o CTA de inscrição deve aparecer como link ativo ou como 'em breve'.", max_length=20, verbose_name='Status das inscrições'),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='short_event_name',
            field=models.CharField(blank=True, default='CBNV 2026', max_length=80, verbose_name='Nome curto'),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='sponsorship_contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail para patrocínios'),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de início'),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='state',
            field=models.CharField(blank=True, default='Minas Gerais', max_length=80, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='submissions_contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail para submissões'),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='venue_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome do local'),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='venue_short_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nome curto do local'),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='youtube_channel_url',
            field=models.URLField(blank=True, verbose_name='Canal do YouTube'),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='youtube_playlist_url',
            field=models.URLField(blank=True, verbose_name='Playlist do YouTube'),
        ),
        migrations.AddConstraint(
            model_name='coresettings',
            constraint=models.UniqueConstraint(fields=('translation_key', 'locale'), name='unique_translation_key_locale_core_coresettings'),
        ),
    ]
