# Generated by Django 6.0.5 on 2026-05-11 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_coresettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='venue_access_notes',
            field=models.TextField(blank=True, verbose_name='Orientações de acesso'),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='venue_address',
            field=models.TextField(blank=True, verbose_name='Endereço oficial do local'),
        ),
    ]
