# Generated by Django 6.0.5 on 2026-05-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_coresettings_venue_access_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='registration_early_bird_deadline',
            field=models.DateField(blank=True, help_text='Data limite para o lote 1 de inscrição.', null=True, verbose_name='Prazo lote 1 (early bird)'),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='registration_early_bird_label',
            field=models.CharField(blank=True, default='Lote 1', max_length=60, verbose_name='Rótulo lote 1'),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='registration_late_label',
            field=models.CharField(blank=True, default='Lote 2', max_length=60, verbose_name='Rótulo lote 2'),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='registration_notes',
            field=models.TextField(blank=True, help_text='Informações adicionais exibidas na página de inscrição.', verbose_name='Observações sobre inscrição'),
        ),
    ]
