# Generated by Django 6.0.5 on 2026-05-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_registration_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='submissions_status',
            field=models.CharField(choices=[('available', 'Disponível'), ('coming_soon', 'Em breve'), ('unavailable', 'Indisponível')], default='coming_soon', help_text='Controla se a criação de novas submissões está aberta, em breve ou fechada.', max_length=20, verbose_name='Status das submissões'),
        ),
    ]
