# Generated by Django 6.0.4 on 2026-05-02 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Subtítulo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Dia do Programa',
                'verbose_name_plural': 'Dias do Programa',
                'ordering': ['sort_order', 'date'],
            },
        ),
        migrations.CreateModel(
            name='ProgramSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Horário início')),
                ('end_time', models.TimeField(verbose_name='Horário fim')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('activity_type', models.CharField(choices=[('reception', 'Recepção'), ('opening_ceremony', 'Mesa Solene'), ('keynote', 'Conferência Plenária'), ('talk', 'Palestra'), ('thematic_session', 'Sessão Temática'), ('poster', 'Sessão de Pôsteres'), ('oral', 'Apresentação Oral'), ('roundtable', 'Mesa-Redonda'), ('break', 'Intervalo'), ('closing_ceremony', 'Encerramento'), ('awards', 'Premiação')], max_length=20, verbose_name='Tipo de atividade')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('room', models.CharField(blank=True, max_length=100, verbose_name='Sala/Local')),
                ('format', models.CharField(choices=[('in_person', 'Presencial'), ('hybrid', 'Híbrido'), ('online', 'Online')], default='in_person', max_length=15, verbose_name='Formato')),
                ('thematic_axis', models.CharField(blank=True, max_length=255, verbose_name='Eixo temático')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('pending', 'Pendente'), ('cancelled', 'Cancelado')], default='draft', max_length=15, verbose_name='Status')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='program.programday', verbose_name='Dia')),
            ],
            options={
                'verbose_name': 'Sessão',
                'verbose_name_plural': 'Sessões',
                'ordering': ['day', 'sort_order', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('display_name', models.CharField(blank=True, max_length=255, verbose_name='Nome de exibição')),
                ('title', models.CharField(blank=True, help_text='Ex: Prof., Dr., Profa. Dra.', max_length=50, verbose_name='Título')),
                ('institution', models.CharField(blank=True, max_length=255, verbose_name='Instituição')),
                ('country', models.CharField(blank=True, max_length=2, verbose_name='País')),
                ('bio', models.TextField(blank=True, verbose_name='Mini-bio')),
                ('lattes_url', models.URLField(blank=True, verbose_name='Lattes')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmado'), ('invited', 'Convidado'), ('pending', 'Pendente'), ('hidden', 'Oculto')], default='pending', max_length=15, verbose_name='Status')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Palestrante',
                'verbose_name_plural': 'Palestrantes',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProgramTalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmado'), ('invited', 'Convidado'), ('pending', 'Pendente'), ('hidden', 'Oculto')], default='pending', max_length=15, verbose_name='Status do palestrante')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talks', to='program.programsession', verbose_name='Sessão')),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talks', to='program.speaker', verbose_name='Palestrante')),
            ],
            options={
                'verbose_name': 'Fala/Apresentação',
                'verbose_name_plural': 'Falas/Apresentações',
                'ordering': ['session', 'sort_order'],
            },
        ),
    ]
