# Generated by Django 6.0.4 on 2026-05-02 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', models.TextField(blank=True, verbose_name='Corpo')),
            ],
            options={
                'verbose_name': 'Página Sobre',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, verbose_name='Introdução')),
                ('cta_text', models.CharField(blank=True, default='Inscreva-se', max_length=255, verbose_name='Texto do CTA')),
                ('cta_link', models.URLField(blank=True, verbose_name='Link do CTA')),
            ],
            options={
                'verbose_name': 'Página Inicial',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('summary', models.CharField(blank=True, max_length=255, verbose_name='Resumo')),
                ('body', models.TextField(blank=True, verbose_name='Corpo')),
                ('featured', models.BooleanField(default=False, verbose_name='Destaque na Home')),
            ],
            options={
                'verbose_name': 'Notícia',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, verbose_name='Introdução')),
            ],
            options={
                'verbose_name': 'Índice de Notícias',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PreviousEditionsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, verbose_name='Introdução')),
            ],
            options={
                'verbose_name': 'Edições Anteriores',
            },
            bases=('wagtailcore.page',),
        ),
    ]
