# Generated by Django 6.0.4 on 2026-05-03 02:58

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_programpage'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('status', models.CharField(choices=[('coming_soon', 'Em breve'), ('open', 'Inscrições Abertas'), ('closed', 'Inscrições Encerradas')], default='coming_soon', max_length=20, verbose_name='Status')),
                ('intro', models.TextField(blank=True, verbose_name='Introdução')),
                ('body', wagtail.fields.StreamField([('text', 0), ('bento_grid', 10)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 3: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'required': False}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('1x1', 'Small (1x1)'), ('2x1', 'Wide (2x1)'), ('1x2', 'Tall (1x2)'), ('2x2', 'Large (2x2)')]}), 8: ('wagtail.blocks.StructBlock', [[('title', 2), ('text', 3), ('image', 4), ('link', 5), ('external_link', 6), ('size', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {}), 10: ('wagtail.blocks.StructBlock', [[('title', 1), ('items', 9)]], {})}, verbose_name='Corpo')),
                ('external_registration_url', models.URLField(blank=True, help_text='Link para a plataforma externa de inscrições', verbose_name='URL Externa de Inscrição')),
            ],
            options={
                'verbose_name': 'Página de Inscrição',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SponsorsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, verbose_name='Introdução')),
            ],
            options={
                'verbose_name': 'Página de Patrocinadores',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SubmissionsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('status', models.CharField(choices=[('coming_soon', 'Em breve'), ('open', 'Submissões Abertas'), ('closed', 'Submissões Encerradas')], default='coming_soon', max_length=20, verbose_name='Status')),
                ('intro', models.TextField(blank=True, verbose_name='Introdução')),
                ('body', wagtail.fields.StreamField([('text', 0), ('bento_grid', 10), ('timeline', 15)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 3: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'required': False}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('1x1', 'Small (1x1)'), ('2x1', 'Wide (2x1)'), ('1x2', 'Tall (1x2)'), ('2x2', 'Large (2x2)')]}), 8: ('wagtail.blocks.StructBlock', [[('title', 2), ('text', 3), ('image', 4), ('link', 5), ('external_link', 6), ('size', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {}), 10: ('wagtail.blocks.StructBlock', [[('title', 1), ('items', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 12: ('wagtail.blocks.TextBlock', (), {'required': False}), 13: ('wagtail.blocks.StructBlock', [[('date', 11), ('title', 2), ('description', 12)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {}), 15: ('wagtail.blocks.StructBlock', [[('title', 1), ('items', 14)]], {})}, verbose_name='Corpo')),
            ],
            options={
                'verbose_name': 'Página de Submissão',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='VideoGalleryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, verbose_name='Introdução')),
            ],
            options={
                'verbose_name': 'Galeria de Vídeos',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='body',
            field=wagtail.fields.StreamField([('text', 0), ('bento_grid', 10), ('stats', 14), ('timeline', 19)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 3: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'required': False}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('1x1', 'Small (1x1)'), ('2x1', 'Wide (2x1)'), ('1x2', 'Tall (1x2)'), ('2x2', 'Large (2x2)')]}), 8: ('wagtail.blocks.StructBlock', [[('title', 2), ('text', 3), ('image', 4), ('link', 5), ('external_link', 6), ('size', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {}), 10: ('wagtail.blocks.StructBlock', [[('title', 1), ('items', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 500+', 'max_length': 20}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Participants', 'max_length': 100}), 13: ('wagtail.blocks.StructBlock', [[('value', 11), ('label', 12)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {}), 15: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 16: ('wagtail.blocks.TextBlock', (), {'required': False}), 17: ('wagtail.blocks.StructBlock', [[('date', 15), ('title', 2), ('description', 16)]], {}), 18: ('wagtail.blocks.ListBlock', (17,), {}), 19: ('wagtail.blocks.StructBlock', [[('title', 1), ('items', 18)]], {})}),
        ),
        migrations.AlterField(
            model_name='newsarticlepage',
            name='body',
            field=wagtail.fields.StreamField([('text', 0), ('image', 1), ('video', 2)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'YouTube link', 'required': False})}),
        ),
    ]
