# Generated by Django 6.0.5 on 2026-05-09 02:37

import django.db.models.deletion
import uuid
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_homepage_hero_image'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('summary', models.CharField(blank=True, max_length=300, verbose_name='Resumo')),
                ('body', wagtail.fields.RichTextField(blank=True, verbose_name='Corpo')),
                ('category', models.CharField(choices=[('general', 'Geral'), ('registration', 'Inscrições'), ('submissions', 'Submissões'), ('program', 'Programação'), ('institutional', 'Institucional')], default='general', max_length=32, verbose_name='Categoria')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de publicação')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', max_length=20, verbose_name='Status')),
                ('featured_on_home', models.BooleanField(default=False, verbose_name='Destaque na Home')),
                ('pinned', models.BooleanField(default=False, verbose_name='Fixar no topo')),
                ('external_url', models.URLField(blank=True, verbose_name='URL externa')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='Título SEO')),
                ('seo_description', models.TextField(blank=True, verbose_name='Descrição SEO')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'verbose_name': 'Notícia ou comunicado',
                'verbose_name_plural': 'Notícias e comunicados',
                'ordering': ['-pinned', '-published_at', 'title'],
                'constraints': [models.UniqueConstraint(fields=('translation_key', 'locale'), name='unique_translation_key_locale_pages_announcement')],
            },
        ),
    ]
