# Generated by Django 6.0.5 on 2026-05-11 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_announcement'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, verbose_name='Introdução')),
            ],
            options={
                'verbose_name': 'Página de Contato',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SpeakerIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, verbose_name='Introdução')),
            ],
            options={
                'verbose_name': 'Página de Palestrantes',
            },
            bases=('wagtailcore.page',),
        ),
    ]
