# Generated by Django 6.0.5 on 2026-05-08 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(blank=True, max_length=255, verbose_name='Instituição')),
                ('country', models.CharField(blank=True, max_length=2, verbose_name='País')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Vínculo/Cargo')),
                ('is_author', models.BooleanField(default=False, verbose_name='Autor')),
                ('is_reviewer', models.BooleanField(default=False, verbose_name='Revisor')),
                ('is_chair', models.BooleanField(default=False, verbose_name='Comissão Científica')),
                ('consent_privacy', models.BooleanField(default=False, verbose_name='Consentimento de privacidade')),
                ('consent_image', models.BooleanField(default=False, verbose_name='Consentimento de uso de imagem')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil de usuário',
                'verbose_name_plural': 'Perfis de usuários',
            },
        ),
    ]
