# Generated by Django 6.0.4 on 2026-05-02 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('category', models.CharField(choices=[('diamond', 'Diamante'), ('gold', 'Ouro'), ('silver', 'Prata'), ('support', 'Apoio')], default='support', max_length=20, verbose_name='Categoria')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Ordem de exibição')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logotipo')),
            ],
            options={
                'verbose_name': 'Patrocinador',
                'verbose_name_plural': 'Patrocinadores',
                'ordering': ['category', 'sort_order', 'name'],
            },
        ),
    ]
