# Generated by Django 6.0.4 on 2026-05-03 02:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={'ordering': ['tier__sort_order', 'sort_order', 'name'], 'verbose_name': 'Patrocinador', 'verbose_name_plural': 'Patrocinadores'},
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='category',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='locale',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsor',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.CreateModel(
            name='SponsorTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True)),
                ('weight', models.PositiveIntegerField(default=2, help_text='Peso visual no grid (ex: 1=Diamante/Grande, 4=Apoio/Pequeno)')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'verbose_name': 'Nível de Patrocínio',
                'verbose_name_plural': 'Níveis de Patrocínio',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='sponsor',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sponsors', to='sponsors.sponsortier', verbose_name='Nível'),
        ),
        migrations.AddConstraint(
            model_name='sponsor',
            constraint=models.UniqueConstraint(fields=('translation_key', 'locale'), name='unique_translation_key_locale_sponsors_sponsor'),
        ),
        migrations.AddConstraint(
            model_name='sponsortier',
            constraint=models.UniqueConstraint(fields=('translation_key', 'locale'), name='unique_translation_key_locale_sponsors_sponsortier'),
        ),
    ]
