# Generated by Django 6.0.5 on 2026-05-09 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_alter_sponsor_options_remove_sponsor_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='category',
            field=models.CharField(choices=[('institutional_partner', 'Parceiro institucional'), ('funding_agency', 'Agência de fomento'), ('scientific_partner', 'Parceiro científico'), ('support', 'Apoio'), ('sponsor', 'Patrocinador'), ('organizing_institution', 'Instituição organizadora')], default='sponsor', max_length=40, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='logo_alt_text',
            field=models.CharField(blank=True, help_text='Descreva o logotipo para tecnologias assistivas quando houver imagem.', max_length=255, verbose_name='Texto alternativo do logotipo'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='show_in_footer',
            field=models.BooleanField(default=False, verbose_name='Exibir no rodapé'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='show_on_about',
            field=models.BooleanField(default=False, verbose_name='Exibir em Sobre'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='show_on_home',
            field=models.BooleanField(default=False, verbose_name='Exibir na Home'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='show_on_sponsorship',
            field=models.BooleanField(default=True, verbose_name='Exibir em Patrocínio'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('hidden', 'Oculto'), ('archived', 'Arquivado')], default='active', max_length=20, verbose_name='Status'),
        ),
    ]
