# Generated by Django 6.0.4 on 2026-05-03 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThematicAxis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Eixo temático',
                'verbose_name_plural': 'Eixos temáticos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.CharField(editable=False, max_length=20, unique=True, verbose_name='ID da submissão')),
                ('title', models.CharField(max_length=500, verbose_name='Título')),
                ('abstract', models.TextField(max_length=2500, verbose_name='Resumo')),
                ('keywords', models.JSONField(default=list, verbose_name='Palavras-chave')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('submitted', 'Enviado'), ('admin_screening', 'Em triagem'), ('assigned_to_reviewers', 'Atribuído a revisores'), ('under_review', 'Em revisão'), ('reviews_completed', 'Revisões concluídas'), ('decision_pending', 'Decisão pendente'), ('accepted_oral', 'Aceito — Oral'), ('accepted_poster', 'Aceito — Pôster'), ('accepted_video', 'Aceito — Vídeo'), ('rejected', 'Rejeitado'), ('final_materials_pending', 'Materiais finais pendentes'), ('ready_for_proceedings', 'Pronto para anais'), ('published_in_proceedings', 'Publicado nos anais')], default='draft', max_length=30, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='Submetedor')),
                ('thematic_axis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='submissions.thematicaxis', verbose_name='Eixo temático')),
            ],
            options={
                'verbose_name': 'Submissão',
                'verbose_name_plural': 'Submissões',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=150, verbose_name='Sobrenome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('institution', models.CharField(max_length=255, verbose_name='Instituição')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_corresponding', models.BooleanField(default=False, verbose_name='Autor correspondente')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='submissions.submission', verbose_name='Submissão')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='Arquivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='submissions.submission', verbose_name='Submissão')),
            ],
            options={
                'verbose_name': 'Arquivo da submissão',
                'verbose_name_plural': 'Arquivos da submissão',
            },
        ),
    ]
