# Generated by Django 6.0.4 on 2026-05-03 18:30

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='decision_notes',
            field=models.TextField(blank=True, verbose_name='Notas da decisão (para o autor)'),
        ),
        migrations.AddField(
            model_name='submission',
            name='final_modality',
            field=models.CharField(blank=True, choices=[('oral', 'Oral'), ('poster', 'Pôster'), ('video', 'Vídeo')], max_length=10, verbose_name='Modalidade final'),
        ),
        migrations.AlterField(
            model_name='submissionfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/home/hugo/Documents/LAPAN/dev/cbnv-website/protected_media')), upload_to='', verbose_name='Arquivo'),
        ),
    ]
