# Generated by Django 6.0.4 on 2026-05-07 14:44

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_submission_decision_notes_submission_final_modality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/app/protected_media')), upload_to='', verbose_name='Arquivo'),
        ),
    ]
