# Generated by Django 6.0.5 on 2026-05-08 20:45

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_alter_submissionfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionfile',
            name='file',
            field=models.FileField(storage=core.storage.ProtectedMediaStorage(), upload_to='', verbose_name='Arquivo'),
        ),
    ]
