# Generated by Django 6.0.4 on 2026-05-03 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0002_submission_decision_notes_submission_final_modality_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Atribuído em')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Aceito em')),
                ('declined_at', models.DateTimeField(blank=True, null=True, verbose_name='Recusado em')),
                ('reviewer', models.ForeignKey(limit_choices_to={'is_reviewer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='review_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Revisor')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_assignments', to='submissions.submission', verbose_name='Submissão')),
            ],
            options={
                'verbose_name': 'Atribuição de revisor',
                'verbose_name_plural': 'Atribuições de revisores',
                'ordering': ['assigned_at'],
                'unique_together': {('reviewer', 'submission')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.CharField(choices=[('accept', 'Aceitar'), ('reject', 'Rejeitar'), ('corrections', 'Aceitar com correções')], max_length=20, verbose_name='Recomendação')),
                ('comments', models.TextField(blank=True, verbose_name='Comentários para o autor')),
                ('confidential_notes', models.TextField(blank=True, verbose_name='Notas confidenciais para a comissão')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='reviews.reviewerassignment', verbose_name='Atribuição')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['submitted_at'],
            },
        ),
    ]
