# Generated by Django 6.0.4 on 2026-05-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='score',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1 = Ruim, 5 = Excelente', null=True, verbose_name='Nota (1-5)'),
        ),
    ]
