# Generated by Django 6.0.5 on 2026-05-08 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewerassignment',
            name='reviewer',
            field=models.ForeignKey(limit_choices_to={'profile__is_reviewer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='review_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Revisor'),
        ),
    ]
